---
- name: install dependencies to enable HTTPS repos
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
