---
- name: install system tools
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - curl
  - dstat
  - htop
  - iftop
  - iotop
  - lsof
  - ltrace
  - mtr
  - net-tools # ie. netstat
  - netcat # nc
  - procps # vmstat, snice, pkill, ...
  - screen
  - strace
  - tcpdump
  - traceroute
  - unzip
  - vim
  - zip
