---
- name: install Fail2ban and its recommended packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - fail2ban
  - iptables
  - whois
  - python3-pyinotify
